### ISSUE TITLE
Необходима реализация как в Kotlin-Android-App через Result<String>

### ISSUE THREAD

**Issue by syoumzic** [JugglypuffM/Kotlin-App-Server#5]
https://github.com/JugglypuffM/Kotlin-App-Server/blob/6e744bf4ca2ac6c13d63cfe4defcc5333eaabc37/src/main/kotlin/auth/Authentificator.kt#L9

https://github.com/JugglypuffM/Kotlin-App-Server/blob/6e744bf4ca2ac6c13d63cfe4defcc5333eaabc37/src/main/kotlin/auth/Authentificator.kt#L17

**Comment by JugglypuffM** [comment]
Господин - не лезьте в прод
Ты прикинь как накладно мне сейчас будет тесты переписывать
Все уже смерджено - ревьюить надо было раньше

**Comment by syoumzic** [comment]
Уговорил, пока отложу

**Comment by JugglypuffM** [comment]
Вообще, честно, тут применима одна фраза "не лезь, оно тебя сожрет" - я по grpc передаю такую же структуру, а изменение на таком глубоком уровне = переписать почти все, что я написал на данный момент

**Comment by syoumzic** [comment]
да там же то же самое что и на Kotlin-Android-App
или нет?

**Comment by JugglypuffM** [comment]
как раз в том и проблема: чтобы переделать AuthResult мне нужно переписать использующий его код на сервере, прото файл, этот прото файл обновить так же на клиенте и после перекомпиляции классов придется переписать корд использующий эти классы там
в сумме получается переписать все что на данный момент есть

**Comment by syoumzic** [comment]
пон, тогда проблема закрыта
